# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  openldap:
    image: bitnami/openldap:2.6.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - './openldap_data:/bitnami/openldap'
  phpldapadmin:
#   image: leenooks/phpldapadmin:2.0.0-dev
#   image: osixia/phpldapadmin:stable
    image: osixia/phpldapadmin:0.9.0
    ports:
      - '8083:80'
    environment:
#     - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
#     - LDAP_HOST=openldap
      - LDAP_PORT=1389
#     - LDAP_USERNAME=cn=admin,dc=example,dc=org
#     - LDAP_PASSWORD=adminpassword
#     - LDAP_BASE_DN=dc=example,dc=org
#     - APP_KEY=base64:3JrewY/3wdVdjKKQxfyh7Zn1gqBzLJfCL3JLfY4n1p4=
    volumes:
      - './phpldapadmin-config.php:/var/www/phpldapadmin/config/config.php'
#     - './phpldapadmin-config.php:/container/service/phpldapadmin/assets/config/config.php'
#     - './phpldapadmin-env.yaml:/container/environment/01-custom/env.yaml'
#     - './phpldapadmin_data/sessions:/var/www/html/storage/framework/sessions'
#     - './phpldapadmin_data/logs:/var/www/html/storage/logs'
  mysql:
    image: mysql:8.1.0
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=keycloak
    volumes:
      - './mysql_data:/var/lib/mysql'
  keycloak:
    image: keycloak/keycloak:22.0.3
    command: 'start-dev'
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=example
      - KC_DB_URL=jdbc:mysql://mysql/keycloak
    depends_on:
      - mysql
  grafana:
    image: grafana/grafana:10.1.1
    ports:
      - '3000:3000'
    environment:
      - ENV_A=admin
    volumes:
      - './grafana_data:/var/lib/grafana'
      - './grafana.ini:/etc/grafana/grafana.ini'
      - './grafana-ldap.toml:/etc/grafana/ldap.toml'
