version: '2'

services:
  kong:
    image: kong:3.7.1
    ports:
      - '8000:8000'
      - '8443:8443'
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=off
     #- KONG_ADMIN_GUI_URL="http://localhost:8002"
    volumes:
      - './kong/kong.yml:/kong/declarative/kong.yml'
     #- '/Users/heqiang/projects/potterhe/apisix-plugin-demo:/usr/local/apisix-plugin-demo'
# httpbin:
#   image: openresty/openresty:1.25.3.1-5-bullseye-fat
#   volumes:
#     - './httpbin/nginx.conf:/etc/nginx/conf.d/default.conf'
